services:
  - type: web
    name: card-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn card_backend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: card_backend.settings
      - key: DATABASE_URL
        value: your_mongodb_url_here
