services:
  - type: web
    name: card-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn card_backend.wsgi
    envVars:
      - key: MONGO_DB_URL
        fromDotEnv: true
